handlers:  
  - name: apply_se
    command: restorecon -RFvv /opt/librenms
  -name: snmpd
    service:
      name: snmpd
      state: restarted
      enabled: yes
  - name: php-fpm
    service:
      name: php-fpm
      state: restarted
      enabled: yes