- name: firewalld
  firewalld:
    service: "{{ item }}"
    zone: public
    permanent: yes
    state: enabled
  loop:
    - http
    - https
- name: firewalld
  firewalld:
    service: "{{ item }}"
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - http
    - https
