- name: git clone
  git:
    repo: https://github.com/librenms/librenms.git
    dest: /opt/librenms
    clone: yes
    update: yes
- name: create librenms system user
  user:
    name: librenms
    shell: /usr/bin/bash
    home: /opt/librenms
    system: yes
    state: present
- name: setfacl
  acl:
    path: "{{ item }}"
    entity: librenms
    etype: group
    permissions: rwx
    recursive: yes
    state: present
  loop:
    - /opt/librenms/rrd
    - /opt/librenms/logs
    - /opt/librenms/bootstrap/cache
    - /opt/librenms/storage/
      
- name: copy cron
  copy:
    src: /opt/librenms/librenms.nonroot.cron
    dest: /etc/cron.d/librenms
    remote_src: yes
    mode: preserve
- name: copy logrotate
  copy:
    src: /opt/librenms/misc/librenms.logrotate
    dest: /etc/logrotate.d/librenms
    remote_src: yes
    mode: preserve

- name: link
  file:
    src: /opt/librenms/lnms
    dest: /usr/local/bin/lnms
    state: link
- name: copy bash
  copy:
    src: /opt/librenms/misc/lnms-completion.bash
    dest: /etc/bash_completion.d/
    remote_src: yes
    mode: preserve

- name: create logfile
  file:
    path: /opt/librenms/logs/librenms.log
    state: touch
    owner: librenms
    group: librenms
  
- name: chown librenms directory
  file:
    path: /opt/librenms
    state: directory
    recurse: yes
    owner: librenms
    group: librenms
    mode: '0771'
