- name: create nginx system user
  user:
    name: nginx
    system: yes
    state: present

- template:
  src: /templates/nginx.conf
  dest: /etc/nginx/nginx.conf

- template:
  src: /templates/nginx-librenms.conf
  dest: /etc/nginx/conf.d/librenms.conf

- name: nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
