- name: create nginx system user
  user:
    name: nginx
    system: yes
    state: present

- name: nginx conf
  template:
    src: /templates/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: nginx-librenms conf
  template:
    src: /templates/nginx-librenms.conf
    dest: /etc/nginx/conf.d/librenms.conf

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
