# cp /etc/php-fpm.d/www.conf /etc/php-fpm.d/librenms.conf

- name: php conf
  template:
    src: php-librenms.conf
    dest: /etc/php-fpm.d/librenms.conf

- name: PHP dependencies
  command: /opt/librenms/scripts/composer_wrapper.php install --no-dev
  become: yes
  become_user: librenms
  notify:
  - php-fpm
