# cp /etc/php-fpm.d/www.conf /etc/php-fpm.d/librenms.conf

- template:
  src: /templates/php-librenms.conf
  dest: /etc/php-fpm.d/librenms.conf

- name: PHP dependencies
  command:
    cmd: /opt/scripts/composer_wrapper.php install --no-dev
    become: yes
    become_user: librenms
    notify:
    - php-fpm
