- name: epel
  dnf: 
    name: epel-release
    state: latest
- name: reset module
  command: dnf module reset php -y
- name: php7.3
  command: dnf module enable php:7.3 -y
- name: yum install all
  dnf: 
    name: "{{ item }}"
    state: latest
    update_cache: True
  loop:
    - bash-completion
    - cronie
    - fping
    - git
    - ImageMagick
    - mariadb-server
    - mtr
    - net-snmp
    - net-snmp-utils
    - nginx
    - nmap
    - php-fpm
    - php-cli
    - php-common
    - php-curl
    - php-gd
    - php-json
    - php-mbstring
    - php-process
    - php-snmp
    - php-xml
    - php-zip
    - php-mysqlnd
    - python3
    - python3-PyMySQL
    - python3-redis
    - python3-memcached
    - python3-pip
    - rrdtool
    - unzip
    - policycoreutils-python-utils
